name: Fix Incorrect URL in All Files
on: [push]

jobs:
  replace_url:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find and Replace Extra Slash in All Files
        run: |
          find . -type f -exec sed -i 's|https://www.futuremarketreport.com//|https://www.futuremarketreport.com/|g' {} +

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "shankarpatil.2444@gmail.com"
          git config --global user.name "Shankar460"
          git add .
          git commit -m "Fixed incorrect URL in all files" || echo "No changes to commit"
          git push origin main
